Connecting join functionality
googleinterns/step244-2020 pull request #37
Opened 2020-09-14 20:44 UTC by andru47

2020-09-14 21:09 UTC, rebekadittrich approved these changes

2020-09-14 21:09 UTC, rebekadittrich commented on src/main/java/com/google/sps/servlets/Utils.java
> +    System.out.println(eventId);
Is this left in from testing?

2020-09-14 21:25 UTC, andru47 commented on src/main/java/com/google/sps/servlets/Utils.java
> +    System.out.println(eventId);
Forgot to delete

2020-09-14 22:49 UTC, LadyPython requested changes

2020-09-14 22:49 UTC, LadyPython commented on src/main/webapp/add_event.html
> +        <input type="checkbox" id="isPublic" name="isPublic" checked="checked" style="width: auto;"><br>
maybe name it is-public and move style to CSS?

2020-09-14 22:49 UTC, LadyPython commented on src/main/webapp/script.js
> +  /*document.getElementById('events-container').innerHTML += '<div><h1>'
Delete this comment

2020-09-15 08:01 UTC, LadyPython approved these changes

2020-09-15 10:21 UTC, marcbury-g approved these changes

2020-09-15 10:40 UTC, merged