Token authentication implementation
googleinterns/step244-2020 pull request #8
Opened 2020-08-19 18:58 UTC by andru47

Add servlets for handling user authentication: redirecting the user to give their consent and redirecting the user back to the original location
Add servlet for verifying the current user's credentials: to be used before calling the Google Calendar API
Add servlet and update script to include starter code on how to talk to the Calendar API

2020-08-21 07:21 UTC, LadyPython requested changes

2020-08-21 07:21 UTC, LadyPython commented on src/main/java/com/google/sps/servlets/CredentialVerifierServlet.java
> +        response.getWriter().print("false");
Maybe do return after this line and do not write "else" further.

2020-08-21 07:21 UTC, LadyPython commented on src/main/java/com/google/sps/servlets/CredentialVerifierServlet.java
> +          response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
The same here.
Like
```suggestion
if (credential == null) {
  response.getWriter().print("false");
  return;
}
if (credential.getAccessToken() == null && credential.refreshToken() == false) {
  response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
  return;
}
response.getWriter().print("true");
```

2020-08-21 07:21 UTC, LadyPython commented on src/main/java/com/google/sps/servlets/OAuth2Callback.java
> +@WebServlet("/oauth2callback")
Why we need this? It seems like /token

2020-08-21 07:21 UTC, LadyPython commented on src/main/webapp/script.js
> +    if (responseText == "true")
return (responseText == "true")?

2020-08-21 09:16 UTC, andru47 commented on src/main/java/com/google/sps/servlets/OAuth2Callback.java
> +@WebServlet("/oauth2callback")
Basically token is a servlet that implements the GoogleAuthorizationCodeFlow. That works like: 
-Check if user has a token
-If it has, then we are done
-If not, send the user to google page to grant permission
But after the user grants permission, they are redirected to callback?query string. And this servlets implements the storing token stuff and redirecting the user back to the original page. If you want more info, you can check: [this](https://googleapis.dev/java/google-oauth-client/latest/com/google/api/client/extensions/servlet/auth/oauth2/AbstractAuthorizationCodeCallbackServlet.html)

2020-08-24 13:16 UTC, pmueller-gg requested changes

2020-08-24 13:16 UTC, pmueller-gg commented on src/main/java/com/google/sps/servlets/Utils.java
> +public class Utils {
It is generally better to use a descriptive name rather than "Utils" (optional)

2020-08-24 13:16 UTC, pmueller-gg commented on src/main/java/com/google/sps/servlets/GCalendarEventsServlet.java
> +    String description = (String) request.getParameter("description");
Is the parameter guaranteed to exist in the request? (Also below)

2020-08-24 13:16 UTC, pmueller-gg commented on src/main/java/com/google/sps/servlets/GCalendarEventsServlet.java
> +    DateTime endDateTime = new DateTime("startTime");
Is that on purpose? If so, it is very confusing.

*start*DateTime = ... "*end*Time"

2020-08-24 13:16 UTC, pmueller-gg commented on src/main/java/com/google/sps/servlets/GCalendarEventsServlet.java
> +    EventDateTime start = new EventDateTime().setDateTime(startDateTime).setTimeZone("Europe/Zurich");
What is the reason to hardcode the time zone here? Will this change in the future? If so, I'd suggest to extract the time zone into a constant, and add a TODO comment, at least.

2020-08-24 13:16 UTC, pmueller-gg commented on src/main/java/com/google/sps/servlets/GCalendarEventsServlet.java
> +    shared.put("field1", "val1"); //To be modifed in the future to get them from param
I suggest to comment the whole line, or use a realistic field name in the dummy data.

2020-08-24 13:16 UTC, pmueller-gg commented on src/main/java/com/google/sps/servlets/GCalendarEventsServlet.java
> +    String calendarId = "c_fmqkfbflaaoqltet2ei7shv184@group.calendar.google.com"; //To be modified with the user's primary
Is this a working example, or will it only work for one user?

2020-08-24 13:16 UTC, pmueller-gg commented on src/main/java/com/google/sps/servlets/OAuth2Callback.java
> +    resp.sendRedirect("http://localhost:8080/" + req.getParameter("origin") + ".html"); //Send user back to the original page
- How will the redirect domain be populated? A constant might make sense here.
- As far as I see, the "origin" parameter is user-controlled. In that case, I suggest to restrict the possible values, e.g. by using an allow-list.

2020-08-24 14:46 UTC, andru47 commented on src/main/java/com/google/sps/servlets/GCalendarEventsServlet.java
> +    DateTime endDateTime = new DateTime("startTime");
It was a bug

2020-08-24 14:47 UTC, andru47 commented on src/main/java/com/google/sps/servlets/GCalendarEventsServlet.java
> +    String description = (String) request.getParameter("description");
If it doesn't exist, it is okay, the description would be empty.

2020-08-24 14:47 UTC, andru47 commented on src/main/java/com/google/sps/servlets/GCalendarEventsServlet.java
> +    EventDateTime start = new EventDateTime().setDateTime(startDateTime).setTimeZone("Europe/Zurich");
I didn't need that, I removed it

2020-08-24 14:48 UTC, andru47 commented on src/main/java/com/google/sps/servlets/GCalendarEventsServlet.java
> +    String calendarId = "c_fmqkfbflaaoqltet2ei7shv184@group.calendar.google.com"; //To be modified with the user's primary
In this pull request I wasn't using the primary calendar, in the next pull request I will do. I can send the next one immediately after the approval of this one.

2020-08-24 14:58 UTC, andru47 commented on src/main/java/com/google/sps/servlets/OAuth2Callback.java
> +    resp.sendRedirect("http://localhost:8080/" + req.getParameter("origin") + ".html"); //Send user back to the original page
The values are restricted from the google cloud platform.

2020-08-24 17:45 UTC, pmueller-gg approved these changes

2020-08-24 17:45 UTC, pmueller-gg commented on src/main/java/com/google/sps/servlets/GCalendarEventsServlet.java
> +    String description = (String) request.getParameter("description");
ok.

2020-08-25 15:22 UTC, LadyPython approved these changes

2020-08-25 15:23 UTC, merged